# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "CORAL Lab"
title:              "CORAL Lab at ASU"
description:        "The CORAL Lab is an natural language processing research group at Arizona State University."


# URL
url:                ""https://username.github.io"
baseurl:            "/asu-coral"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  # - name:           "about"
  #   href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
